// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ConfirmController from "./confirm_controller.js"
application.register("confirm", ConfirmController)

import FormController from "./form_controller.js"
application.register("form", FormController)
