// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ConfirmController from "./confirm_controller.js"
application.register("confirm", ConfirmController)

import FormController from "./form_controller.js"
application.register("form", FormController)

import SearchController from "./search_controller.js"
application.register("search", SearchController)

import TagListController from "./tag_list_controller.js"
application.register("tag-list", TagListController)
